FROM python:3.11.12@sha256:a3e280261e448b95d49423532ccd6e5329c39d171c10df1457891ff7c5e2301b
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
# Don't copy app - will be volume mounted
CMD ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]